# -Dconfiguration.properties=interdependencies.configuration.properties

household.ARITHMODYNAMIC.number = 2000
household.lifespanInDays = 29200
household.retirementAgeInDays = 23725
# retirementSaving=true in combination with key interest rate > 0 can cause ad-hoc inflation due to interest on saving deposits
household.retirementSaving = false
household.numberOfLabourHoursPerDay = 16
household.newHouseholdFromAgeInDays = 6570
household.newHouseholdEveryXDays = 1825
household.requiredUtilityPerDay = 1.0
household.daysWithoutUtilityUntilDestructor = 60
household.maxPricePerUnitMultiplier = 1.0

factory.capitalDepreciationRatioPerPeriod = 0.001 
# significantly determining stability of prices; too much money capital -> volatile markets 
factory.referenceCredit = 10000
factory.margin = 0.1

factory.ARITHMODYNAMIC.IRON.number = 10
factory.ARITHMODYNAMIC.COAL.number = 10
factory.ARITHMODYNAMIC.COTTON.number = 10
factory.ARITHMODYNAMIC.WHEAT.number = 10
factory.ARITHMODYNAMIC.FOOD.number = 10
factory.ARITHMODYNAMIC.CLOTHING.number = 10
factory.ARITHMODYNAMIC.KILOWATT.number = 10
factory.ARITHMODYNAMIC.REALESTATE.number = 10
factory.ARITHMODYNAMIC.MACHINE.number = 3



centralBank.reserveRatio = 0.1
centralBank.inflationTarget = 0.02
centralBank.targetPriceIndex = 15
# negative key interest rates can cause abnormal behaviour, e. g. a flow of interest from pension saving bank accounts into the monetary system 
# (which is a problem, as i. e. hoarded money that has been neutralized by credit banks buying state bonds and 
# states buying goods, thereby reintroducing the hoarded money into the monetary system -> expanding M1 -> instable prices)
centralBank.minEffectiveKeyInterestRate = 0.0
centralBank.maxEffectiveKeyInterestRate = 0.05
centralBank.defaultEffectiveKeyInterestRate = 0.02
centralBank.statisticalOffice.priceIndexWeights.IRON = 0.125
centralBank.statisticalOffice.priceIndexWeights.COAL = 0.125
centralBank.statisticalOffice.priceIndexWeights.COTTON = 0.125
centralBank.statisticalOffice.priceIndexWeights.WHEAT = 0.125
centralBank.statisticalOffice.priceIndexWeights.FOOD = 0.125
centralBank.statisticalOffice.priceIndexWeights.CLOTHING = 0.125
centralBank.statisticalOffice.priceIndexWeights.KILOWATT = 0.125
centralBank.statisticalOffice.priceIndexWeights.REALESTATE = 0.125

centralBank.ARITHMODYNAMIC.number = 1

creditBank.ARITHMODYNAMIC.number = 5
creditBank.priceChangeIncrement = 0.1
creditBank.maxCreditForCurrencyTrading = 100000
creditBank.minArbitrageMargin = 0.03

trader.ARITHMODYNAMIC.number = 10
trader.arbitrageMargin = 0.2
trader.referenceCredit = 10000

state.ARITHMODYNAMIC.number = 1
state.bondMargin = 0.02

agent.balanceSheetPublicationHourType = HOUR_23

budgetingBehaviour.internalRateOfReturn = 0.05
budgetingBehaviour.keyInterestRateTransmissionDamper = 50

inputOutputModel = InputOutputModelInterdependencies

jointStockCompany.initialNumberOfShares = 100

pricingBehaviour.defaultPriceChangeIncrementExplicit = 0.05
pricingBehaviour.defaultPriceChangeIncrementImplicit = 0.001
# stability: number of prices should be > 5 
pricingBehaviour.defaultNumberOfPrices = 7
pricingBehaviour.defaultInitialPrice = 5.0

timeSystem.initializationPhaseInDays = 180

dashboard.log.numberOfAgentsLogSize = 500

# significantly determines stability of prices! numberOfIterations = 20 leads to strong volatility in credit utilization rate -> volatile M1 -> volatile prices
math.numberOfIterations = 100
math.initializationValue = 0.0000001